//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSR_Web_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string MediaType { get; set; }
        public string Source { get; set; }
        public Nullable<int> DisplayPosition { get; set; }
        public string Media { get; set; }
        public int Section_Id { get; set; }
        public int Veteran_Id { get; set; }
    
        public virtual Section Section { get; set; }
    }
}
