//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSR_Web_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Section()
        {
            this.Contents = new HashSet<Content>();
        }
    
        public int Id { get; set; }
        public string EventTitle { get; set; }
        public bool Approved { get; set; }
        public int DisplayPosition { get; set; }
        public string CoordY { get; set; }
        public string CoordX { get; set; }
        public string Message { get; set; }
        public string CameraZoom { get; set; }
        public int Fk_Veterans_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Content> Contents { get; set; }
        public virtual Veteran Veteran { get; set; }
    }
}
