//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSR_Web_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veteran
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Veteran()
        {
            this.Sections = new HashSet<Section>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string Surname { get; set; }
        public string DOB { get; set; }
        public string BirthPlace { get; set; }
        public string Death { get; set; }
        public string MaritalStatus { get; set; }
        public string EnlistedDate { get; set; }
        public string EmbarkmentAge { get; set; }
        public string RegimentNumber { get; set; }
        public string Battalion { get; set; }
        public string Religion { get; set; }
        public string Address { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string ShortBio { get; set; }
        public string Fate { get; set; }
        public Nullable<int> Status { get; set; }
        public byte[] ProfilePicture { get; set; }
        public Nullable<int> Fk_User_Id { get; set; }
        public Nullable<int> Fk_Veteran_Queue_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Section> Sections { get; set; }
        public virtual User User { get; set; }
        public virtual VeteranQueue VeteranQueue { get; set; }
    }
}
